azure:
  activedirectory:
    b2c:
      base-uri: https://Enter_the_Tenant_Subdomain_Here.b2clogin.com/Enter_the_Tenant_Subdomain_Here.onmicrosoft.com/
      client-id: Enter_the_Application_Id_Here
      client-secret: Enter_the_Client_Secret_Here 
      logout-success-url: http://localhost:8080/
      user-flows:
        sign-up-or-sign-in: b2c_1_susi
        profile-edit: b2c_1_edit_profile
        password-reset: b2c_1_reset
      user-name-attribute-name: name

app:
  protect:
    authenticated: /token_details


# un-comment the following lines if you are deploying to a reverse proxy (e.g. Azure App Service)
# server:
#   forward-headers-strategy: native
#   tomcat:
#     remoteip:
#       protocol-header: "X-Forwarded-Proto"
#       remote-ip-header: "X-Forwarded-For"
#       internal-proxies: ".*"
